notifications:
  email:
    on_success: never
    on_failure: never
sudo: required
services:
  - docker
script:
  - docker build -t hlag/https-proxy:latest .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
