notifications:
  email:
    on_success: never
    on_failure: never
sudo: required
services:
  - docker
script:
  - docker build -t hlag/https-proxy:latest .
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
  - docker push hlag/https-proxy:latest
